<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Productivity Report</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #14b8a6; /* Teal-500 */
            padding-bottom: 20px;
        }
        .header h1 {
            color: #0f172a; /* Slate-900 */
            margin: 0;
            font-size: 24px;
            text-transform: uppercase;
            letter-spacing: 2px;
        }
        .header p {
            color: #64748b; /* Slate-500 */
            margin: 5px 0 0;
            font-size: 14px;
        }
        .card-grid {
            display: table;
            width: 100%;
            margin-bottom: 30px;
        }
        .card {
            display: table-cell;
            width: 30%;
            background: #f8fafc; /* Slate-50 */
            padding: 15px;
            text-align: center;
            border-radius: 10px;
            border: 1px solid #e2e8f0;
        }
        .card h3 {
            margin: 0;
            font-size: 32px;
            color: #14b8a6;
        }
        .card span {
            display: block;
            font-size: 12px;
            color: #64748b;
            text-transform: uppercase;
            font-weight: bold;
        }
        .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
            border-left: 4px solid #f59e0b; /* Amber-500 */
            padding-left: 10px;
            margin-bottom: 15px;
            margin-top: 30px;
        }
        .insight-box {
            background: #eff6ff; /* Blue-50 */
            border: 1px solid #bfdbfe;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .insight-box p {
            margin: 0;
            font-size: 14px;
        }
        .ai-comment {
            background: #1e293b; /* Slate-800 */
            color: white;
            padding: 20px;
            border-radius: 10px;
            margin-top: 40px;
            position: relative;
        }
        .ai-comment h4 {
            margin: 0 0 10px;
            color: #14b8a6;
            text-transform: uppercase;
            font-size: 12px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }
        th {
            text-align: left;
            border-bottom: 1px solid #cbd5e1;
            padding: 8px;
            color: #64748b;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #f1f5f9;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Weekly Productivity Report</h1>
        <p>{{ $user->name }} &bull; {{ $date_range }}</p>
    </div>

    <!-- Key Metrics -->
    <div class="card-grid">
        <div class="card">
            <h3>{{ $total_minutes }}</h3>
            <span>Focus Minutes</span>
        </div>
        <div class="card" style="width: 5%;"></div> <!-- Spacer -->
        <div class="card">
            <h3>{{ $total_tasks }}</h3>
            <span>Tasks Completed</span>
        </div>
        <div class="card" style="width: 5%;"></div> <!-- Spacer -->
        <div class="card">
            <h3>{{ $insights['best_day'] }}</h3>
            <span>Best Day</span>
        </div>
    </div>

    <div class="section-title">Weekly Breakdown</div>
    <table>
        <thead>
            <tr>
                <th>Day</th>
                <th>Focus Time</th>
                <th>Tasks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($trends as $day)
            <tr>
                <td>{{ $day['day_name'] }}</td>
                <td>{{ $day['focus_minutes'] }} min</td>
                <td>{{ $day['tasks_completed'] }} tasks</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="ai-comment">
        <h4>🤖 AI Assistant Feedback</h4>
        <p>"{{ $ai_comment }}"</p>
    </div>

    <div class="footer">
        Generated by Pomodoro Assistant on {{ date('Y-m-d H:i') }}
    </div>

</body>
</html>
